// src/dfx/assets/project_templates/react/src/__frontend_name__/src/App.jsx
import { useState } from 'react';
import { __backend_name_ident__ } from 'declarations/__backend_name__';

function App() {
  const [greeting, setGreeting] = useState('');

  async function handleSubmit(event) {
    event.preventDefault();
    const name = event.target.elements.name.value;
    const greeting = await __backend_name_ident__.greet(name);
    setGreeting(greeting);
    return false;
  }

  return (
    <main className="container">
      <div className="card">
        <h1>{greeting}</h1>
        <form action="#" onSubmit={handleSubmit}>
          <label htmlFor="name">Enter your name:</label>
          <input type="text" id="name" required />
          <button type="submit">Click Me!</button>
        </form>
        <img src="/logo.svg" alt="DFINITY logo" width="256" />
      </div>
    </main>
  );
}

export default App;

// src/dfx/assets/project_templates/vue/src/__frontend_name__/src/App.vue
<script setup>
import { ref } from 'vue';
import { __backend_name_ident__ } from 'declarations/__backend_name__/index';

let greeting = ref('');

async function handleSubmit(e) {
  e.preventDefault();
  const target = e.target;
  const name = target.querySelector('#name').value;
  greeting.value = await __backend_name_ident__.greet(name);
}
</script>

<template>
  <main class="container">
    <div class="card">
      <h1>{{ greeting }}</h1>

      <form action="#" @submit="handleSubmit">
        <label for="name">Enter your name:</label>
        <input type="text" id="name" required />
        <button type="submit">Click Me!</button>
      </form>

      <img src="/logo.svg" alt="DFINITY logo" width="256" />
    </div>
  </main>
</template>
